### ISSUE TITLE
App crashes when loading release notes

### ISSUE THREAD

**Issue by euptron** [euptron/CodeOps-Studio#2]
## Problem Description

The app crashes with a `NullPointerException` in the `LogAdapter` when attempting to append a `null` CharSequence in the `onBindViewHolder()` method during RecyclerView binding. This occurs when the log data contains `null` values.

## Steps to Reproduce the Behavior

1. Open the Releases notes and quickly leave it before the data is synced

### Expected Behavior
- No crash or unexpected behavior when accessing the release notes.

## Crash Details

- **Crash Date:** Sun Sep 08 2024 20:31:58 GMT+0100 (West Africa Standard Time)

<details><summary>Crashlytics Issue ID</summary>
<p>

```
50dfb50c980fcffba644e7fa8debbafd
```  

</p>
</details>

- **Thread:** `main`
- **Exception:** `java.lang.NullPointerException`  
  **Message:**  
  ```
  java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
  ```
  
  This error occurs when trying loading release notes into the `ChangeLogAdapter` as a result of a null object reference.
## Stack Trace

```java
Non-fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
       at android.text.SpannableStringBuilder.append(SpannableStringBuilder.java:269)
       at com.eup.codeopsstudio.logging.LogAdapter.onBindViewHolder(LogAdapter.java:85)
       at com.eup.codeopsstudio.logging.LogAdapter.onBindViewHolder(LogAdapter.java:40)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:640)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
       at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
       at android.view.View.measure(View.java:23608)
       at android.widget.HorizontalScrollView.measureChildWithMargins(HorizontalScrollView.java:1287)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.widget.HorizontalScrollView.onMeasure(HorizontalScrollView.java:323)
       at android.view.View.measure(View.java:23608)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6960)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23608)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6960)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
       at android.view.View.measure(View.java:23608)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6960)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23608)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9384)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1653)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1828)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
       at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:576)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
       at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
       at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2365)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1828)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1828)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1828)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:883)
       at android.view.View.layout(View.java:21093)
       at android.view.ViewGroup.layout(ViewGroup.java:6400)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3363)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2804)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1804)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8218)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1047)
       at android.view.Choreographer.doCallbacks(Choreographer.java:859)
       at android.view.Choreographer.doFrame(Choreographer.java:791)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1033)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:7212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

## System Information

- **Package Name:** `com.eup.codeopsstudio`
- **App Version:** `1.0.0 (1)`

**Comment by euptron** [comment]
Fixed issue
