### ISSUE TITLE
App crashes when handling back press in SettingsPane

### ISSUE THREAD

**Issue by euptron** [euptron/CodeOps-Studio#3]
## Problem Description

The app encounters a `NullPointerException` in the `SettingsPane` class when attempting to check if a `Fragment` is the primary navigation. The issue occurs when the `equals()` method is called on a null `Fragment` object in the `isPrimaryNavigation()` method. This leads to a crash when handling the back press event in the settings pane, causing the app to fail during navigation operations.

## Steps to Reproduce the Behavior

1. Open the app and navigate to the settings pane.
2. Trigger a back press event (e.g., by pressing the back button).
3. Observe the crash, which occurs when the app tries to handle the back press due to a null `Fragment` in the `isPrimaryNavigation()` method.

### Expected Behavior
- The app should handle the back press event smoothly in the settings pane without crashing. The `Fragment` should be properly checked for null before calling the `equals()` method, ensuring proper navigation handling.

## Crash Details

- **Crash Date:** Wed Sep 04 2024 08:59:52 GMT+0100 (West Africa Standard Time)

<details><summary>Crashlytics Issue ID</summary>
<p>

```
516de67b0dd6824a7aec7f8bd411974d
```  

</p>
</details>

- **Thread:** `main`
- **Exception:** `java.lang.NullPointerException`  
  **Message:**  
  ```
  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.fragment.app.Fragment.equals(java.lang.Object)' on a null object reference
  ```
  
This error occurs when attempting to handle a back press event in the `SettingsPane` due to a null `Fragment` being passed to the `equals()` method in the `isPrimaryNavigation()` check.
## Stack Trace

```java
Non-fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.fragment.app.Fragment.equals(java.lang.Object)' on a null object reference
       at com.eup.codeopsstudio.ui.settings.SettingsPane.isPrimaryNavigation(SettingsPane.java:92)
       at com.eup.codeopsstudio.ui.settings.SettingsPane$1.handleOnBackPressed(SettingsPane.java:80)
       at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.kt:276)
       at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:678)
       at android.app.Activity.onKeyUp(Activity.java:3905)
       at android.view.KeyEvent.dispatch(KeyEvent.java:3688)
       at android.app.Activity.dispatchKeyEvent(Activity.java:4230)
       at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.kt:103)
       at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
       at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.kt:117)
       at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3397)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:823)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7722)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7545)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6922)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7143)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7200)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7176)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7363)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3399)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2960)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2951)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3376)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:186)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

## System Information

- **Package Name:** `com.eup.codeopsstudio`
- **App Version:** `1.0.0 (1)`

**Comment by euptron** [comment]
Fixed issue
